apiVersion: v1
kind: PersistentVolume

metadata:
  name: prom-pv
  labels:
    type: local

spec:
  storageClassName: mystorage
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: "/mnt/sda1/data/prometheus"
    